# Generated by Django 5.2 on 2026-10-07 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('registered', 'Registered'), ('status_confirmed', 'Investor confirmed professional status (text C)'), ('mandate_saved', 'Investor saved the mandate for the first time'), ('mandate_changed', 'Investor changed the mandate'), ('deck_uploaded', 'Startup uploaded a pitch deck'), ('ai_draft_created', 'AI finished the teaser draft'), ('field_edited', 'Teaser Field Edited'), ('teaser_approved', 'Teaser Approved'), ('went_live', 'Went live')], db_index=True, max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
