# Generated by Django 5.2 on 2026-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('registered', 'Registered'), ('status_confirmed', 'Investor confirmed professional status (text C)'), ('mandate_saved', 'Investor saved the mandate for the first time'), ('mandate_changed', 'Investor changed the mandate'), ('deck_uploaded', 'Startup uploaded a pitch deck'), ('ai_draft_created', 'AI finished the teaser draft')], db_index=True, max_length=50),
        ),
    ]
