# Generated by Django 5.2 on 2026-10-08 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='entity_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='entity_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('system', 'System')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('registered', 'Registered'), ('status_confirmed', 'Investor confirmed status (text C)'), ('mandate_saved', 'Investor saved mandate (v1)'), ('mandate_changed', 'Investor changed mandate (vX)'), ('deck_uploaded', 'Startup uploaded pitch deck'), ('ai_draft_created', 'AI finished teaser draft'), ('field_edited', 'Teaser field edited'), ('teaser_approved', 'Teaser approved'), ('went_live', 'Went live')], db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user_id', 'created_at'], name='idx_events_user_time'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name', 'created_at'], name='idx_events_name_time'),
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
