services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:5173"
