# Generated by Django 5.2 on 2026-10-08 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        ('startups', '0002_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email_verification', 'E-mail verification'), ('password_reset', 'Password reset'), ('draft_ready', 'Draft ready'), ('draft_deletion_reminder', 'Draft deletion reminder'), ('digest', 'Digest'), ('digest_empty', 'Empty digest'), ('introduction_request', 'Introduction request (D)'), ('introduction', 'Introduction (E)'), ('survey_invite', 'Survey invite')], max_length=32)),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English'), ('uk', 'Ukrainian')], default='de', max_length=2)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='QUEUED', max_length=8)),
                ('provider_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('digest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_notifications', to='matching.digest')),
                ('introduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_notifications', to='matching.introduction')),
                ('startup_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_notifications', to='startups.startupprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_email_queue'), models.Index(fields=['user', 'type', 'created_at'], name='idx_email_user_type')],
            },
        ),
    ]
