# Generated by Django 5.2 on 2026-10-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_choices_drop_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
