# Generated by Django 5.2 on 2026-10-03 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('removed', 'Removed')], default='draft', max_length=20)),
                ('sector', models.CharField(choices=[('fintech', 'Fintech'), ('healthtech', 'Healthtech')], max_length=30)),
                ('stage', models.CharField(choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A')], max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('amount_seeking', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mrr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('team_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
