# Generated by Django 5.2 on 2026-10-07 13:54

import django.contrib.postgres.functions
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], db_default='DRAFT', default='DRAFT', max_length=8)),
                ('sector_other_text', models.CharField(blank=True, max_length=100, null=True)),
                ('business_model_other_text', models.CharField(blank=True, max_length=100, null=True)),
                ('round_amount_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mrr_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('growth_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('team_size', models.SmallIntegerField(blank=True, null=True)),
                ('draft_expires_at', models.DateTimeField(blank=True, null=True)),
                ('went_live_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_by', models.CharField(blank=True, choices=[('startup', 'Startup'), ('system', 'System (30 days)'), ('staff', 'Staff (reports)')], max_length=8, null=True)),
                ('moderation_hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_model', models.ForeignKey(blank=True, db_column='business_model_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.businessmodel')),
                ('country', models.ForeignKey(blank=True, db_column='country_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.country')),
                ('sector', models.ForeignKey(blank=True, db_column='sector_code', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.sector')),
                ('stage', models.ForeignKey(blank=True, db_column='stage_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.stage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_profiles',
            },
        ),
        migrations.CreateModel(
            name='StartupPrivateDetails',
            fields=[
                ('startup_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='private_details', serialize=False, to='startups.startupprofile')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'startup_private_details',
            },
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(condition=models.Q(('moderation_hidden_at__isnull', True), ('status', 'LIVE')), fields=['sector', 'stage', 'country'], name='idx_startup_matching'),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(condition=models.Q(('status', 'DRAFT')), fields=['draft_expires_at'], name='idx_startup_draft_expiry'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'LIVE', 'PAUSED', 'REMOVED'])), name='chk_startup_profiles_status'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(('sector_other_text__isnull', True), ('sector', 'other'), _connector='OR'), name='chk_startup_profiles_sector_other'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(('business_model_other_text__isnull', True), ('business_model', 'other'), _connector='OR'), name='chk_startup_profiles_bm_other'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('round_amount_eur__isnull', True), ('round_amount_eur__gt', 0), _connector='OR'), models.Q(('mrr_eur__isnull', True), ('mrr_eur__gte', 0), _connector='OR')), name='chk_startup_profiles_amounts'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(('team_size__isnull', True), ('team_size__gte', 1), _connector='OR'), name='chk_startup_profiles_team'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REMOVED']), models.Q(('business_model__isnull', False), ('country__isnull', False), ('round_amount_eur__isnull', False), ('sector__isnull', False), ('stage__isnull', False), ('team_size__isnull', False), ('went_live_at__isnull', False)), _connector='OR'), name='chk_startup_profiles_live_complete'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAUSED'), _negated=True), ('paused_at__isnull', False), _connector='OR'), name='chk_startup_profiles_paused'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removed_at__isnull', False), ('removed_by__isnull', False), ('status', 'REMOVED')), models.Q(models.Q(('status', 'REMOVED'), _negated=True), ('removed_at__isnull', True), ('removed_by__isnull', True)), _connector='OR'), name='chk_startup_profiles_removed'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(condition=models.Q(('removed_by__isnull', True), ('removed_by__in', ['startup', 'system', 'staff']), _connector='OR'), name='chk_startup_profiles_removed_by'),
        ),
    ]
