# Generated by Django 5.2 on 2026-10-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='business_model',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
