# Generated by Django 5.2 on 2026-10-08 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_country_chk_countries_code_and_more'),
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In review'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=12)),
                ('decision', models.CharField(blank=True, choices=[('no_action', 'No action'), ('profile_hidden', 'Profile hidden'), ('profile_removed', 'Profile removed')], max_length=16, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reporter_notified_at', models.DateTimeField(blank=True, null=True)),
                ('startup_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_decided', to=settings.AUTH_USER_MODEL)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.reporttype')),
                ('reporter_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='startups.startupprofile')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['startup_profile', 'status'], name='idx_reports_profile_status'), models.Index(fields=['status', 'created_at'], name='idx_reports_status_created')],
                'constraints': [models.UniqueConstraint(fields=('startup_profile', 'reporter_user'), name='uq_reports_reporter')],
            },
        ),
    ]
