# Generated by Django 5.2 on 2026-10-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_pitchdeck_startup'),
        ('startups', '0002_startupprofile_business_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartupProfile',
        ),
    ]
