# Generated by Django 5.2 on 2026-10-08 18:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_remove_country_chk_countries_code_and_more'),
        ('documents', '0003_remove_teaserfield_chk_teaser_fields_name_and_more'),
        ('investors', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('period_start', models.DateField(help_text='Понедельник недели дайджеста')),
                ('card_count', models.PositiveSmallIntegerField(default=0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('first_open_channel', models.CharField(blank=True, choices=[('email', 'E-mail'), ('cabinet', 'Cabinet')], max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digests', to='investors.investorprofile')),
            ],
            options={
                'db_table': 'digests',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('INTERESTED', 'Interested'), ('ACCEPTED', 'Accepted'), ('INTRODUCED', 'Introduced'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='SUGGESTED', max_length=12)),
                ('suggested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interested_at', models.DateTimeField(blank=True, null=True)),
                ('investor_message', models.CharField(blank=True, max_length=500, null=True)),
                ('request_expires_at', models.DateTimeField(blank=True, null=True)),
                ('startup_responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('introduced_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('declined_by', models.CharField(blank=True, choices=[('investor', 'Investor'), ('startup', 'Startup')], max_length=8, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decline_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.declinereason')),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='introductions', to='investors.investorprofile')),
                ('mandate', models.ForeignKey(help_text='Версия мандата, на основе которой произошел матч', on_delete=django.db.models.deletion.PROTECT, related_name='introductions', to='investors.mandate')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='introductions', to='startups.startupprofile')),
                ('teaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='introductions', to='documents.teaser')),
            ],
            options={
                'db_table': 'introductions',
            },
        ),
        migrations.CreateModel(
            name='DigestCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Позиция в дайджесте от 1 до 5')),
                ('match_reason_codes', models.JSONField(default=list, help_text='Коды причин совпадения: sector, stage, region, check_size, business_model')),
                ('soft_match_count', models.PositiveSmallIntegerField(default=0)),
                ('profile_age_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='matching.digest')),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='matching.introduction')),
            ],
            options={
                'db_table': 'digest_cards',
                'ordering': ['digest', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='digest',
            constraint=models.UniqueConstraint(fields=('investor_profile', 'period_start'), name='uq_digests_week'),
        ),
        migrations.AddIndex(
            model_name='introduction',
            index=models.Index(fields=['startup_profile', 'status'], name='idx_intro_startup_status'),
        ),
        migrations.AddIndex(
            model_name='introduction',
            index=models.Index(fields=['investor_profile', 'status'], name='idx_intro_investor_status'),
        ),
        migrations.AddIndex(
            model_name='introduction',
            index=models.Index(fields=['status', 'request_expires_at'], name='idx_intro_expiry'),
        ),
        migrations.AddConstraint(
            model_name='introduction',
            constraint=models.UniqueConstraint(fields=('investor_profile', 'startup_profile'), name='uq_introductions_pair'),
        ),
        migrations.AddIndex(
            model_name='digestcard',
            index=models.Index(fields=['introduction'], name='idx_digest_cards_intro'),
        ),
        migrations.AddConstraint(
            model_name='digestcard',
            constraint=models.UniqueConstraint(fields=('digest', 'position'), name='uq_digest_cards_position'),
        ),
        migrations.AddConstraint(
            model_name='digestcard',
            constraint=models.UniqueConstraint(fields=('digest', 'introduction'), name='uq_digest_cards_intro'),
        ),
    ]
