# Generated by Django 5.2 on 2026-10-07 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectors', models.JSONField(default=list)),
                ('stages', models.JSONField(default=list)),
                ('regions', models.JSONField(default=list)),
                ('ticket_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ticket_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('business_models', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_mandate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
