# Generated by Django 5.2 on 2026-10-08 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_remove_country_chk_countries_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_person_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.country')),
                ('investor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.investortype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investor_profiles',
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('check_min_eur', models.DecimalField(decimal_places=2, max_digits=14)),
                ('check_max_eur', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('criterion_suggestion', 'Accepted suggestion')], default='manual', max_length=24)),
                ('sector_codes', models.JSONField(default=list)),
                ('stage_codes', models.JSONField(default=list)),
                ('country_codes', models.JSONField(default=list)),
                ('region_codes', models.JSONField(blank=True, default=list)),
                ('business_model_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='investors.investorprofile')),
            ],
            options={
                'db_table': 'mandates',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('investor_profile', 'version'), name='uq_mandates_version'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('investor_profile',), name='uq_mandates_single_current')],
            },
        ),
    ]
