# Generated by Django 5.2 on 2026-10-08 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_country_chk_countries_code_and_more'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=32)),
                ('decline_count', models.PositiveSmallIntegerField(default=1)),
                ('shown_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.declinereason')),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterion_suggestions', to='investors.investorprofile')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterion_suggestions', to='investors.mandate')),
            ],
            options={
                'db_table': 'criterion_suggestions',
                'ordering': ['-shown_at'],
                'indexes': [models.Index(fields=['investor_profile', 'shown_at'], name='idx_crit_sugg_investor')],
            },
        ),
    ]
