# Generated by Django 5.2 on 2026-10-07 13:54

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('staff', 'Staff')], max_length=16)),
                ('preferred_language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('uk', 'Українська')], default='de', max_length=2)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A — Erklärung des Startups'), ('B', 'B — Hinweis auf dem Teaser'), ('C', 'C — Bestätigung Investor'), ('D', 'D — Anfrage an das Startup'), ('E', 'E — Signatur Intro-E-Mail'), ('F', 'F — Auswahlkriterien'), ('G', 'G — Hinweis KI'), ('AGB', 'AGB'), ('DSE', 'Datenschutzerklärung')], max_length=8)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], max_length=2)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('legal_approved_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'legal_documents',
                'unique_together': {('code', 'language', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('registration', 'Registration (AGB, DSE)'), ('teaser_approval', 'Teaser approval (A)'), ('investor_status', 'Investor status (C)')], max_length=24)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('legal_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='accounts.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_consents',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'created_at'], name='idx_users_role_created'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', 'context'], name='idx_user_consents_user'),
        ),
    ]
