# Generated by Django 5.2.17 on 2026-10-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='document_type',
            field=models.CharField(choices=[('agb', 'AGB'), ('datenschutz', 'Datenschutz'), ('investor-status', 'Investor status (text C)')], max_length=20),
        ),
    ]
