# Generated by Django 5.2 on 2026-10-06 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_consent_document_type'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A — Erklärung des Startups'), ('B', 'B — Hinweis auf dem Teaser'), ('C', 'C — Bestätigung Investor'), ('D', 'D — Anfrage an das Startup'), ('E', 'E — Signatur Intro-E-Mail'), ('F', 'F — Auswahlkriterien'), ('G', 'G — Hinweis KI'), ('AGB', 'AGB'), ('DSE', 'Datenschutzerklärung')], max_length=8)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], max_length=2)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('legal_approved_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'legal_documents',
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('registration', 'Registration (AGB, DSE)'), ('teaser_approval', 'Teaser approval (A)'), ('investor_status', 'Investor status (C)')], max_length=24)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_consents',
            },
        ),
        migrations.RemoveField(
            model_name='consent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('uk', 'Українська')], default='de', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('staff', 'Staff')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'created_at'], name='idx_users_role_created'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together={('code', 'language', 'version')},
        ),
        migrations.AddField(
            model_name='userconsent',
            name='legal_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='accounts.legaldocument'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Consent',
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', 'context'], name='idx_user_consents_user'),
        ),
    ]
