# Generated by Django 6.1 on 2026-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('join_date', models.DateField(verbose_name='Дата вступу')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний')], default='active', max_length=20, verbose_name='Статус')),
                ('is_founder', models.BooleanField(default=False, verbose_name='Засновник')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
