# Generated by Django 6.1 on 2026-08-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
    ]
