# Generated by Django 5.2 on 2026-10-07 13:56

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, storage=common.utils.get_private_storage, upload_to=common.utils.deck_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('rejected', 'Rejected')], default='ok', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeaserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('DRAFT_READY', 'Draft Ready'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('draft', models.JSONField(blank=True, null=True)),
                ('risk_phrases', models.JSONField(blank=True, default=list)),
                ('cost_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('original_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='documents.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('risk_phrases', models.JSONField(blank=True, default=list)),
                ('reviewed', models.JSONField(blank=True, default=list)),
                ('edited', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10)),
                ('declaration_a_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaser', to='documents.teaserjob')),
            ],
        ),
    ]
