# Generated by Django 5.2 on 2026-10-07 16:20

import common.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, storage=common.utils.get_private_storage, upload_to=common.utils.deck_upload_path)),
                ('storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('original_name', models.CharField(default='deck.pdf', max_length=255)),
                ('mime_type', models.CharField(db_default='application/pdf', default='application/pdf', max_length=100)),
                ('file_size_bytes', models.BigIntegerField()),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('keep_original', models.BooleanField(db_default=False, default=False)),
                ('keep_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_state', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('DRAFT_READY', 'Draft ready'), ('FAILED', 'Failed')], db_default='QUEUED', default='QUEUED', max_length=12)),
                ('attempt_count', models.SmallIntegerField(db_default=0, default=0)),
                ('failure_reason', models.CharField(blank=True, choices=[('pdf_unreadable', 'PDF unreadable'), ('invalid_response', 'Invalid AI response'), ('provider_unavailable', 'Provider unavailable'), ('other', 'Other')], max_length=24, null=True)),
                ('ai_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=30, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('ai_cost_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_finished_at', models.DateTimeField(blank=True, null=True)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, choices=[('auto_24h', 'Auto after 24h'), ('profile_removed', 'Profile removed'), ('user_request', 'User request'), ('replaced', 'Replaced'), ('processing_failed', 'Processing failed')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pitch_decks', to='startups.startupprofile')),
            ],
            options={
                'db_table': 'pitch_decks',
            },
        ),
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], db_default='DRAFT', default='DRAFT', max_length=12)),
                ('is_current', models.BooleanField(db_default=False, default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declaration_consent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_teaser', to='accounts.userconsent')),
                ('pitch_deck', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaser', to='documents.pitchdeck')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teasers', to='startups.startupprofile')),
            ],
            options={
                'db_table': 'teasers',
            },
        ),
        migrations.CreateModel(
            name='TeaserField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('headline', 'Headline'), ('problem', 'Problem description'), ('solution', 'Solution description'), ('market', 'Market & Competition'), ('traction', 'Traction & Metrics'), ('team_description', 'Team description'), ('business_description', 'Business description')], max_length=32)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2)),
                ('ai_text', models.TextField(blank=True, null=True)),
                ('final_text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(db_default=False, default=False)),
                ('risk_phrases', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.teaser')),
            ],
            options={
                'db_table': 'teaser_fields',
            },
        ),
        migrations.AddIndex(
            model_name='pitchdeck',
            index=models.Index(fields=['startup_profile'], name='idx_pitch_decks_profile'),
        ),
        migrations.AddIndex(
            model_name='pitchdeck',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('keep_original', False)), fields=['delete_after'], name='idx_pitch_decks_delete_due'),
        ),
        migrations.AddIndex(
            model_name='pitchdeck',
            index=models.Index(condition=models.Q(('processing_state__in', ['QUEUED', 'PROCESSING'])), fields=['processing_state', 'uploaded_at'], name='idx_pitch_decks_queue'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(('mime_type', 'application/pdf')), name='chk_pitch_decks_mime'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(('file_size_bytes__gt', 0), models.Q(('page_count__isnull', True), ('page_count__gt', 0), _connector='OR')), name='chk_pitch_decks_size'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('keep_original', True), _negated=True), ('keep_confirmed_at__isnull', False), _connector='OR'), name='chk_pitch_decks_keep'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(('deletion_reason__isnull', True), ('deletion_reason__in', ['auto_24h', 'profile_removed', 'user_request', 'replaced', 'processing_failed']), _connector='OR'), name='chk_pitch_decks_deletion_reason'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(('processing_state__in', ['QUEUED', 'PROCESSING', 'DRAFT_READY', 'FAILED'])), name='chk_pitch_decks_state'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('processing_state', 'FAILED'), _negated=True), ('failure_reason__isnull', False), _connector='OR'), name='chk_pitch_decks_failure'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(('failure_reason__isnull', True), ('failure_reason__in', ['pdf_unreadable', 'invalid_response', 'provider_unavailable', 'other']), _connector='OR'), name='chk_pitch_decks_failure_reason'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('processing_state__in', ['DRAFT_READY', 'FAILED']), _negated=True), ('processing_finished_at__isnull', False), _connector='OR'), name='chk_pitch_decks_finished'),
        ),
        migrations.AddConstraint(
            model_name='pitchdeck',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0), models.Q(('input_tokens__isnull', True), ('input_tokens__gte', 0), _connector='OR'), models.Q(('output_tokens__isnull', True), ('output_tokens__gte', 0), _connector='OR'), models.Q(('ai_cost_eur__isnull', True), ('ai_cost_eur__gte', 0), _connector='OR')), name='chk_pitch_decks_ai_numbers'),
        ),
        migrations.AddConstraint(
            model_name='teaser',
            constraint=models.UniqueConstraint(fields=('startup_profile', 'version'), name='uq_teasers_version'),
        ),
        migrations.AddConstraint(
            model_name='teaser',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'APPROVED', 'SUPERSEDED'])), name='chk_teasers_status'),
        ),
        migrations.AddConstraint(
            model_name='teaser',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='chk_teasers_version'),
        ),
        migrations.AddConstraint(
            model_name='teaser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('declaration_consent__isnull', True), ('status', 'DRAFT')), models.Q(models.Q(('status', 'DRAFT'), _negated=True), ('approved_at__isnull', False), ('declaration_consent__isnull', False)), _connector='OR'), name='chk_teasers_approval'),
        ),
        migrations.AddConstraint(
            model_name='teaser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('startup_profile',), name='uq_teasers_current'),
        ),
        migrations.AddConstraint(
            model_name='teaserfield',
            constraint=models.UniqueConstraint(fields=('teaser', 'field_name', 'language'), name='uq_teaser_fields'),
        ),
        migrations.AddConstraint(
            model_name='teaserfield',
            constraint=models.CheckConstraint(condition=models.Q(('field_name__in', ['headline', 'problem', 'solution', 'market', 'traction', 'team_description', 'business_description'])), name='chk_teaser_fields_name'),
        ),
        migrations.AddConstraint(
            model_name='teaserfield',
            constraint=models.CheckConstraint(condition=models.Q(('language__in', ['de', 'en'])), name='chk_teaser_fields_language'),
        ),
        migrations.AddConstraint(
            model_name='teaserfield',
            constraint=models.CheckConstraint(condition=models.Q(('approved_at__isnull', True), ('final_text__isnull', False), _connector='OR'), name='chk_teaser_fields_approved'),
        ),
    ]
