# Generated by Django 5.2 on 2026-10-03 12:25

import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='decks/%Y/%m/', validators=[common.validators.validate_deck_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeaserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('DRAFT_READY', 'Draft Ready'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('draft', models.JSONField(blank=True, null=True)),
                ('risk_phrases', models.JSONField(blank=True, default=list)),
                ('cost_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='documents.pitchdeck')),
            ],
        ),
    ]
