# Generated by Django 5.2 on 2026-10-03 12:39

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchdeck',
            name='file',
            field=models.FileField(blank=True, upload_to='decks/%Y/%m/', validators=[common.validators.validate_deck_file]),
        ),
    ]
