# Generated by Django 5.2 on 2026-10-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teaser',
            name='chk_teasers_approval',
        ),
        migrations.AddConstraint(
            model_name='teaser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('declaration_consent__isnull', True), ('status', 'DRAFT')), models.Q(('approved_at__isnull', False), ('declaration_consent__isnull', False), ('status', 'APPROVED')), ('status', 'SUPERSEDED'), _connector='OR'), name='chk_teasers_approval'),
        ),
    ]
