# Generated by Django 5.2 on 2026-10-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_teaser_chk_teasers_approval_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teaserfield',
            name='chk_teaser_fields_name',
        ),
        migrations.AlterField(
            model_name='teaserfield',
            name='field_name',
            field=models.CharField(choices=[('headline', 'Headline'), ('problem', 'Problem'), ('solution', 'Solution'), ('market', 'Market'), ('traction', 'Traction'), ('team', 'Team'), ('team_description', 'Team description'), ('business_description', 'Business description')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='teaserfield',
            constraint=models.CheckConstraint(condition=models.Q(('field_name__in', ['headline', 'problem', 'solution', 'market', 'traction', 'team', 'team_description', 'business_description'])), name='chk_teaser_fields_name'),
        ),
    ]
