# Generated by Django 5.2 on 2026-10-03 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_teaser'),
        ('profiles', '0006_alter_startupprofile_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchdeck',
            name='startup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.startupprofile'),
        ),
    ]
