# Generated by Django 5.2 on 2026-10-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_pitchdeck_startup'),
        ('profiles', '0006_alter_startupprofile_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaserjob',
            name='deck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='profiles.deck'),
        ),
        migrations.AddField(
            model_name='teaserjob',
            name='original_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PitchDeck',
        ),
    ]
