# Generated by Django 5.2 on 2026-10-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorType',
            fields=[
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'investor_types',
                'ordering': ['sort_order', 'name_de'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'regions',
                'ordering': ['sort_order', 'name_de'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'report_types',
                'ordering': ['sort_order', 'name_de'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'stages',
                'ordering': ['sort_order', 'name_de'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_other', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'db_table': 'business_models',
                'ordering': ['sort_order', 'name_de'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_other', True)), fields=('is_other',), name='uq_business_models_other')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['sort_order', 'name_de'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z]{2,10}$')), name='chk_countries_code')],
            },
        ),
        migrations.CreateModel(
            name='DeclineReason',
            fields=[
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('mandate_criterion', models.CharField(blank=True, choices=[('sector', 'Sector'), ('stage', 'Stage'), ('region', 'Region'), ('check_size', 'Check size')], max_length=16, null=True)),
            ],
            options={
                'db_table': 'decline_reasons',
                'ordering': ['sort_order', 'name_de'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('mandate_criterion__isnull', True), ('mandate_criterion__in', ['sector', 'stage', 'region', 'check_size']), _connector='OR'), name='chk_decline_reasons_criterion')],
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('detection', models.CharField(choices=[('llm', 'LLM'), ('regex', 'Regex'), ('image', 'Image')], max_length=8)),
                ('action', models.CharField(choices=[('remove', 'Remove'), ('generalize', 'Generalize'), ('highlight', 'Highlight')], max_length=12)),
                ('regex_pattern', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'risk_categories',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^R[0-9]{2}$')), name='chk_risk_categories_code'), models.CheckConstraint(condition=models.Q(('detection__in', ['llm', 'regex', 'image'])), name='chk_risk_categories_detection'), models.CheckConstraint(condition=models.Q(('action__in', ['remove', 'generalize', 'highlight'])), name='chk_risk_categories_action'), models.CheckConstraint(condition=models.Q(models.Q(('detection', 'regex'), _negated=True), ('regex_pattern__isnull', False), _connector='OR'), name='chk_risk_categories_regex')],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('name_de', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('sort_order', models.SmallIntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_other', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'db_table': 'sectors',
                'ordering': ['sort_order', 'name_de'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_other', True)), fields=('is_other',), name='uq_sectors_other')],
            },
        ),
    ]
