# Generated by Django 5.2 on 2026-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='country',
            name='chk_countries_code',
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[a-z]{2,10}$')), name='chk_countries_code'),
        ),
    ]
