# Generated by Django 6.1 on 2026-08-29 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_member_created_at_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Billing Period'),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source Name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='completed', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member', verbose_name='Member'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date', 'status'], name='idx_payment_date_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['type', 'date'], name='idx_payment_type_date'),
        ),
    ]
