# Generated by Django 6.1 on 2026-08-31 08:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_member_created_at_and_more'),
        ('payments', '0002_alter_payment_options_payment_amount_payment_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Платіж', 'verbose_name_plural': 'Платежі'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date(2026, 1, 1), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.member', verbose_name='Член'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Період'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва джерела'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('owed', 'Заборговано')], db_index=True, default='paid', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('membership_fee', 'Членський внесок'), ('donation', 'Пожертва'), ('sponsorship', 'Спонсорська підтримка'), ('grant', 'Грант')], db_index=True, max_length=50, verbose_name='Тип надходження'),
        ),
    ]
